services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: NoteQ
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-net

  backend:
    build: ./backend
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - backend-net
        
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      VITE_BACKEND_URL: "http://backend:${PORT}"
    env_file:
      - .env
    depends_on:
      - mysql
      - backend
    networks:
      - backend-net
      
volumes:
  mysql-data:

networks:
  backend-net: